### ISSUE TITLE
Any plans to publish this to pypi?

### ISSUE THREAD

**Issue by sunnz** [wied03/centos-package-cron#15]
So that it can be installed via pip?

**Comment by wied03** [comment]
I figured most people would prefer the RPM route due to dependencies like yum-plugin-changelog and sqlite. I actually submitted this for inclusion in the CentOS developer repo but I'm not sure what they decided.

I have no objection to it but am short on time. If someone could examine setup.py to see if it needs any tweaks before the actual push to pypi, that would be great.

**Comment by sunnz** [comment]
Yes I agree with RPM route. Pypi would be nice to have especially when we don't know what the CentOS dev have decided yet.

**Comment by sunnz** [comment]
I understand everyone have priorities that may not be able to work on this right now, and I am ok with just installing from source for now too... so I just wanted to raise this issue so that it can be considered. :-)

**Comment by stephane-martin** [comment]
I think pypi would be nice if we could generalize centos-package-cron to other distributions (detect security patches for centos, redhat, debian, ubuntu). Then sysadmins could install through pypi on every machine whatever the distrib would be. I will need that function in my job, so I'll probably propose a PR, but not very soon.

**Comment by wied03** [comment]
RHEL has this covered already through yum security last time I checked. I can't remember if apticron on Ubuntu does this already but I think it does. I'm not sure it makes sense if those other distros have it covered already, does it?

Another approach to this problem is what coreos/clair is doing where they scan the RPM database and have their own CVE patching. Right now it's built for docker only but I wonder if that might change.

**Comment by wied03** [comment]
That's an interesting discussion but not to forget the original issue, I'm OK with publishing to pypi.

**Comment by wied03** [comment]
Moved other discussion to https://github.com/wied03/centos-package-cron/issues/19

**Comment by stephane-martin** [comment]
For pip install, there may be a problem related to rpmUtils too. That python package is included in the yum RPM AFAIK.

**Comment by wied03** [comment]
I'm tinkering around with https://testpypi.python.org/pypi/centos_package_cron/1.0.8.1 this morning

**Comment by wied03** [comment]
Went ahead and kept it simple for now. Added just the SQL alchemy dependency and updated README.

https://pypi.python.org/pypi/centos_package_cron/1.0.8.1
